export default {
  citiesBySpell: {
    A: [
      { code: "0997", name: "阿克苏", spell: "Akesu", label: "Akesu0997" },
      { code: "0837", name: "阿坝", spell: "Aba", label: "Aba0837" },
      {
        code: "0483",
        name: "阿拉善盟",
        spell: "Alashanmeng",
        label: "Alashanmeng0483",
      },
      { code: "0906", name: "阿勒泰", spell: "Aletai", label: "Aletai0906" },
      { code: "0897", name: "阿里", spell: "Ali", label: "Ali0897" },
      { code: "0915", name: "安康", spell: "Ankang", label: "Ankang0915" },
      { code: "0556", name: "安庆", spell: "Anqing", label: "Anqing0556" },
      { code: "0412", name: "鞍山", spell: "Anshan", label: "Anshan0412" },
      { code: "0853", name: "安顺", spell: "Anshun", label: "Anshun0853" },
      { code: "0372", name: "安阳", spell: "Anyang", label: "Anyang0372" },
      { code: "0796", name: "安福", spell: "Anfu", label: "Anfu0796" },
      { code: "0572", name: "安吉", spell: "Anji", label: "Anji0572" },
      { code: "0871", name: "安宁", spell: "Anning", label: "Anning0871" },
      { code: "0536", name: "安丘", spell: "Anqiu", label: "Anqiu0536" },
      { code: "0595", name: "安溪", spell: "Anxi", label: "Anxi0595" },
      { code: "0791", name: "安义", spell: "Anyi", label: "Anyi0791" },
      { code: "0797", name: "安远", spell: "Anyuan", label: "Anyuan0797" },
    ],
    B: [
      { code: "010", name: "北京", spell: "Beijing", label: "Beijing010" },
      {
        code: "0436",
        name: "白城",
        spell: "Baicheng",
        label: "Baicheng0436",
      },
      { code: "0776", name: "百色", spell: "Baise", label: "Baise0776" },
      {
        code: "0439",
        name: "白山",
        spell: "Baishan",
        label: "Baishan0439",
      },
      { code: "0943", name: "白银", spell: "Baiyin", label: "Baiyin0943" },
      { code: "0552", name: "蚌埠", spell: "Bangbu", label: "Bangbu0552" },
      {
        code: "0312",
        name: "保定",
        spell: "Baoding",
        label: "Baoding0312",
      },
      { code: "0917", name: "宝鸡", spell: "Baoji", label: "Baoji0917" },
      {
        code: "0875",
        name: "保山",
        spell: "Baoshan",
        label: "Baoshan0875",
      },
      { code: "0472", name: "包头", spell: "Baotou", label: "Baotou0472" },
      {
        code: "0478",
        name: "巴彦淖尔",
        spell: "Bayannaoer",
        label: "Bayannaoer0478",
      },
      {
        code: "0996",
        name: "巴音郭楞",
        spell: "Bayinguoleng",
        label: "Bayinguoleng0996",
      },
      {
        code: "0827",
        name: "巴中",
        spell: "Bazhong",
        label: "Bazhong0827",
      },
      { code: "0779", name: "北海", spell: "Beihai", label: "Beihai0779" },
      { code: "0414", name: "本溪", spell: "Benxi", label: "Benxi0414" },
      { code: "0857", name: "毕节", spell: "Bijie", label: "Bijie0857" },
      {
        code: "0543",
        name: "滨州",
        spell: "Binzhou",
        label: "Binzhou0543",
      },
      {
        code: "0909",
        name: "博尔塔拉",
        spell: "Boertala",
        label: "Boertala0909",
      },
      { code: "0558", name: "亳州", spell: "Bozhou", label: "Bozhou0558" },
      {
        code: "0514",
        name: "宝应",
        spell: "Baoying",
        label: "Baoying0514",
      },
      { code: "0515", name: "滨海", spell: "Binhai", label: "Binhai0515" },
      { code: "0391", name: "博爱", spell: "Boai", label: "Boai0391" },
      { code: "0752", name: "博罗", spell: "Boluo", label: "Boluo0752" },
    ],
    C: [
      {
        code: "023",
        name: "重庆",
        spell: "Chongqing",
        label: "Chongqing023",
      },
      {
        code: "0431",
        name: "长春",
        spell: "Changchun",
        label: "Changchun0431",
      },
      {
        code: "0731",
        name: "长沙",
        spell: "Changsha",
        label: "Changsha0731",
      },
      {
        code: "0519",
        name: "常州",
        spell: "Changzhou",
        label: "Changzhou0519",
      },
      { code: "028", name: "成都", spell: "Chengdu", label: "Chengdu028" },
      {
        code: "0317",
        name: "沧州",
        spell: "Cangzhou",
        label: "Cangzhou0317",
      },
      {
        code: "0736",
        name: "常德",
        spell: "Changde",
        label: "Changde0736",
      },
      {
        code: "0895",
        name: "昌都",
        spell: "Changdu",
        label: "Changdu0895",
      },
      {
        code: "0355",
        name: "长治",
        spell: "Changzhi",
        label: "Changzhi0355",
      },
      { code: "0565", name: "巢湖", spell: "Chaohu", label: "Chaohu0565" },
      {
        code: "0421",
        name: "朝阳",
        spell: "Chaoyang",
        label: "Chaoyang0421",
      },
      {
        code: "0768",
        name: "潮州",
        spell: "Chaozhou",
        label: "Chaozhou0768",
      },
      {
        code: "0314",
        name: "承德",
        spell: "Chengde",
        label: "Chengde0314",
      },
      {
        code: "0735",
        name: "郴州",
        spell: "Chenzhou",
        label: "Chenzhou0735",
      },
      {
        code: "0476",
        name: "赤峰",
        spell: "Chifeng",
        label: "Chifeng0476",
      },
      {
        code: "0566",
        name: "池州",
        spell: "Chizhou",
        label: "Chizhou0566",
      },
      {
        code: "0550",
        name: "滁州",
        spell: "Chuzhou",
        label: "Chuzhou0550",
      },
      {
        code: "0577",
        name: "苍南",
        spell: "Cangnan",
        label: "Cangnan0577",
      },
      {
        code: "0539",
        name: "苍山",
        spell: "Cangshan",
        label: "Cangshan0539",
      },
      {
        code: "0530",
        name: "曹县",
        spell: "Caoxian",
        label: "Caoxian0530",
      },
      {
        code: "0535",
        name: "长岛",
        spell: "Changdao",
        label: "Changdao0535",
      },
      {
        code: "0551",
        name: "长丰",
        spell: "Changfeng",
        label: "Changfeng0551",
      },
      {
        code: "0411",
        name: "长海",
        spell: "Changhai",
        label: "Changhai0411",
      },
      {
        code: "0591",
        name: "长乐",
        spell: "Changle",
        label: "Changle0591",
      },
      {
        code: "0570",
        name: "常山",
        spell: "Changshan",
        label: "Changshan0570",
      },
      {
        code: "0512",
        name: "常熟",
        spell: "Changshu",
        label: "Changshu0512",
      },
      {
        code: "0596",
        name: "长泰",
        spell: "Changtai",
        label: "Changtai0596",
      },
      {
        code: "0597",
        name: "长汀",
        spell: "Changting",
        label: "Changting0597",
      },
      {
        code: "0635",
        name: "茌平",
        spell: "Chiping",
        label: "Chiping0635",
      },
      {
        code: "0794",
        name: "崇仁",
        spell: "Chongren",
        label: "Chongren0794",
      },
      { code: "0571", name: "淳安", spell: "Chunan", label: "Chunan0571" },
      { code: "0574", name: "慈溪", spell: "Cixi", label: "Cixi0574" },
      { code: "020", name: "从化", spell: "Conghua", label: "Conghua020" },
    ],
    D: [
      {
        code: "0769",
        name: "东莞",
        spell: "Dongguan",
        label: "Dongguan0769",
      },
      { code: "0872", name: "大理", spell: "Dali", label: "Dali0872" },
      {
        code: "0415",
        name: "丹东",
        spell: "Dandong",
        label: "Dandong0415",
      },
      { code: "0459", name: "大庆", spell: "Daqing", label: "Daqing0459" },
      { code: "0352", name: "大同", spell: "Datong", label: "Datong0352" },
      {
        code: "0457",
        name: "大兴安岭",
        spell: "Daxinganling",
        label: "Daxinganling0457",
      },
      { code: "0818", name: "达州", spell: "Dazhou", label: "Dazhou0818" },
      { code: "0692", name: "德宏", spell: "Dehong", label: "Dehong0692" },
      { code: "0838", name: "德阳", spell: "Deyang", label: "Deyang0838" },
      { code: "0534", name: "德州", spell: "Dezhou", label: "Dezhou0534" },
      { code: "0932", name: "定西", spell: "Dingxi", label: "Dingxi0932" },
      { code: "0887", name: "迪庆", spell: "Diqing", label: "Diqing0887" },
      {
        code: "0546",
        name: "东营",
        spell: "Dongying",
        label: "Dongying0546",
      },
      {
        code: "0580",
        name: "岱山",
        spell: "Daishan",
        label: "Daishan0580",
      },
      {
        code: "0557",
        name: "砀山",
        spell: "Dangshan",
        label: "Dangshan0557",
      },
      { code: "0555", name: "当涂", spell: "Dangtu", label: "Dangtu0555" },
      {
        code: "0511",
        name: "丹阳",
        spell: "Danyang",
        label: "Danyang0511",
      },
      { code: "0753", name: "大埔", spell: "Dapu", label: "Dapu0753" },
      { code: "0598", name: "大田", spell: "Datian", label: "Datian0598" },
      { code: "0792", name: "德安", spell: "Dean", label: "Dean0792" },
      {
        code: "0371",
        name: "登封",
        spell: "Dengfeng",
        label: "Dengfeng0371",
      },
      { code: "0758", name: "德庆", spell: "Deqing", label: "Deqing0758" },
      { code: "0793", name: "德兴", spell: "Dexing", label: "Dexing0793" },
      {
        code: "0668",
        name: "电白",
        spell: "Dianbai",
        label: "Dianbai0668",
      },
      {
        code: "0518",
        name: "东海",
        spell: "Donghai",
        label: "Donghai0518",
      },
      {
        code: "0538",
        name: "东平",
        spell: "Dongping",
        label: "Dongping0538",
      },
      {
        code: "0579",
        name: "东阳",
        spell: "Dongyang",
        label: "Dongyang0579",
      },
      {
        code: "0762",
        name: "东源",
        spell: "Dongyuan",
        label: "Dongyuan0762",
      },
    ],
    E: [
      { code: "0718", name: "恩施", spell: "Enshi", label: "Enshi0718" },
      {
        code: "0477",
        name: "鄂尔多斯",
        spell: "Eerduosi",
        label: "Eerduosi0477",
      },
      { code: "0711", name: "鄂州", spell: "Ezhou", label: "Ezhou0711" },
      { code: "0750", name: "恩平", spell: "Enping", label: "Enping0750" },
    ],
    F: [
      { code: "0413", name: "抚顺", spell: "Fushun", label: "Fushun0413" },
      { code: "0757", name: "佛山", spell: "Foshan", label: "Foshan0757" },
      {
        code: "0770",
        name: "防城港",
        spell: "Fangchenggang",
        label: "Fangchenggang0770",
      },
      { code: "0418", name: "阜新", spell: "Fuxin", label: "Fuxin0418" },
      { code: "024", name: "法库", spell: "Faku", label: "Faku024" },
      {
        code: "0553",
        name: "繁昌",
        spell: "Fanchang",
        label: "Fanchang0553",
      },
      {
        code: "0795",
        name: "丰城",
        spell: "Fengcheng",
        label: "Fengcheng0795",
      },
      {
        code: "0554",
        name: "凤台",
        spell: "Fengtai",
        label: "Fengtai0554",
      },
      {
        code: "0516",
        name: "丰县",
        spell: "Fengxian",
        label: "Fengxian0516",
      },
      { code: "0790", name: "分宜", spell: "Fenyi", label: "Fenyi0790" },
      { code: "0763", name: "佛冈", spell: "Fogang", label: "Fogang0763" },
      { code: "0593", name: "福安", spell: "Fuan", label: "Fuan0593" },
      {
        code: "0798",
        name: "浮梁",
        spell: "Fuliang",
        label: "Fuliang0798",
      },
    ],
    G: [
      { code: "0941", name: "甘南", spell: "Gannan", label: "Gannan0941" },
      {
        code: "0851",
        name: "贵阳",
        spell: "Guiyang",
        label: "Guiyang0851",
      },
      { code: "0836", name: "甘孜", spell: "Ganzi", label: "Ganzi0836" },
      {
        code: "0826",
        name: "广安",
        spell: "Guangan",
        label: "Guangan0826",
      },
      {
        code: "0839",
        name: "广元",
        spell: "Guangyuan",
        label: "Guangyuan0839",
      },
      {
        code: "0775",
        name: "贵港",
        spell: "Guigang",
        label: "Guigang0775",
      },
      { code: "0773", name: "桂林", spell: "Guilin", label: "Guilin0773" },
      { code: "0975", name: "果洛", spell: "Guoluo", label: "Guoluo0975" },
      { code: "0954", name: "固原", spell: "Guyuan", label: "Guyuan0954" },
      {
        code: "0311",
        name: "藁城",
        spell: "Gaocheng",
        label: "Gaocheng0311",
      },
      { code: "025", name: "高淳", spell: "Gaochun", label: "Gaochun025" },
      { code: "0931", name: "皋兰", spell: "Gaolan", label: "Gaolan0931" },
      { code: "029", name: "高陵", spell: "Gaoling", label: "Gaoling029" },
      {
        code: "0533",
        name: "高青",
        spell: "Gaoqing",
        label: "Gaoqing0533",
      },
      {
        code: "0563",
        name: "广德",
        spell: "Guangde",
        label: "Guangde0563",
      },
      {
        code: "0599",
        name: "光泽",
        spell: "Guangze",
        label: "Guangze0599",
      },
      { code: "0701", name: "贵溪", spell: "Guixi", label: "Guixi0701" },
    ],
    H: [
      { code: "0970", name: "海北", spell: "Haibei", label: "Haibei0970" },
      {
        code: "0451",
        name: "哈尔滨",
        spell: "Haerbin",
        label: "Haerbin0451",
      },
      { code: "0898", name: "海口", spell: "Haikou", label: "Haikou0898" },
      { code: "0310", name: "邯郸", spell: "Handan", label: "Handan0310" },
      {
        code: "0972",
        name: "海东",
        spell: "Haidong",
        label: "Haidong0972",
      },
      { code: "0974", name: "海南", spell: "Hainan", label: "Hainan0974" },
      { code: "0977", name: "海西", spell: "Haixi", label: "Haixi0977" },
      { code: "0902", name: "哈密", spell: "Hami", label: "Hami0902" },
      {
        code: "0916",
        name: "汉中",
        spell: "Hanzhong",
        label: "Hanzhong0916",
      },
      { code: "0392", name: "鹤壁", spell: "Hebi", label: "Hebi0392" },
      { code: "0778", name: "河池", spell: "Hechi", label: "Hechi0778" },
      { code: "0468", name: "鹤岗", spell: "Hegang", label: "Hegang0468" },
      { code: "0456", name: "黑河", spell: "Heihe", label: "Heihe0456" },
      {
        code: "0318",
        name: "衡水",
        spell: "Hengshui",
        label: "Hengshui0318",
      },
      {
        code: "0734",
        name: "衡阳",
        spell: "Hengyang",
        label: "Hengyang0734",
      },
      {
        code: "0903",
        name: "和田地",
        spell: "Hetiandi",
        label: "Hetiandi0903",
      },
      { code: "0774", name: "贺州", spell: "Hezhou", label: "Hezhou0774" },
      { code: "0873", name: "红河", spell: "Honghe", label: "Honghe0873" },
      { code: "0517", name: "淮安", spell: "Huaian", label: "Huaian0517" },
      {
        code: "0561",
        name: "淮北",
        spell: "Huaibei",
        label: "Huaibei0561",
      },
      {
        code: "0745",
        name: "怀化",
        spell: "Huaihua",
        label: "Huaihua0745",
      },
      {
        code: "0713",
        name: "黄冈",
        spell: "Huanggang",
        label: "Huanggang0713",
      },
      {
        code: "0973",
        name: "黄南",
        spell: "Huangnan",
        label: "Huangnan0973",
      },
      {
        code: "0559",
        name: "黄山",
        spell: "Huangshan",
        label: "Huangshan0559",
      },
      {
        code: "0714",
        name: "黄石",
        spell: "Huangshi",
        label: "Huangshi0714",
      },
      {
        code: "0471",
        name: "呼和浩特",
        spell: "Huhehaote",
        label: "Huhehaote0471",
      },
      {
        code: "0429",
        name: "葫芦岛",
        spell: "Huludao",
        label: "Huludao0429",
      },
      {
        code: "0470",
        name: "呼伦贝尔",
        spell: "Hulunbeier",
        label: "Hulunbeier0470",
      },
      { code: "0513", name: "海安", spell: "Haian", label: "Haian0513" },
      {
        code: "0660",
        name: "海丰",
        spell: "Haifeng",
        label: "Haifeng0660",
      },
      {
        code: "0573",
        name: "海宁",
        spell: "Haining",
        label: "Haining0573",
      },
      {
        code: "0423",
        name: "桦甸",
        spell: "Huadian",
        label: "Huadian0423",
      },
      { code: "0663", name: "惠来", spell: "Huilai", label: "Huilai0663" },
      { code: "0564", name: "霍邱", spell: "Huoqiu", label: "Huoqiu0564" },
    ],
    J: [
      {
        code: "0454",
        name: "佳木斯",
        spell: "Jiamusi",
        label: "Jiamusi0454",
      },
      { code: "0531", name: "济南", spell: "Jinan", label: "Jinan0531" },
      {
        code: "0937",
        name: "嘉峪关",
        spell: "Jiayuguan",
        label: "Jiayuguan0937",
      },
      {
        code: "0935",
        name: "金昌",
        spell: "Jinchang",
        label: "Jinchang0935",
      },
      {
        code: "0356",
        name: "晋城",
        spell: "Jincheng",
        label: "Jincheng0356",
      },
      {
        code: "0724",
        name: "荆门",
        spell: "Jingmen",
        label: "Jingmen0724",
      },
      {
        code: "0716",
        name: "荆州",
        spell: "Jingzhou",
        label: "Jingzhou0716",
      },
      { code: "0537", name: "济宁", spell: "Jining", label: "Jining0537" },
      {
        code: "0354",
        name: "晋中",
        spell: "Jinzhong",
        label: "Jinzhong0354",
      },
      {
        code: "0416",
        name: "锦州",
        spell: "Jinzhou",
        label: "Jinzhou0416",
      },
      { code: "0467", name: "鸡西", spell: "Jixi", label: "Jixi0467" },
      {
        code: "0523",
        name: "姜堰",
        spell: "Jiangyan",
        label: "Jiangyan0523",
      },
      {
        code: "0510",
        name: "江阴",
        spell: "Jiangyin",
        label: "Jiangyin0510",
      },
      {
        code: "0532",
        name: "胶南",
        spell: "Jiaonan",
        label: "Jiaonan0532",
      },
      {
        code: "0578",
        name: "景宁",
        spell: "Jingning",
        label: "Jingning0578",
      },
      { code: "0633", name: "莒县", spell: "Juxian", label: "Juxian0633" },
    ],
    K: [
      {
        code: "0378",
        name: "开封",
        spell: "Kaifeng",
        label: "Kaifeng0378",
      },
      {
        code: "0998",
        name: "喀什地",
        spell: "Kashidi",
        label: "Kashidi0998",
      },
      {
        code: "0990",
        name: "克拉玛依",
        spell: "Kelamayi",
        label: "Kelamayi0990",
      },
      { code: "0908", name: "克孜勒", spell: "Kezile", label: "Kezile0908" },
    ],
    L: [
      { code: "0772", name: "来宾", spell: "Laibin", label: "Laibin0772" },
      {
        code: "0379",
        name: "洛阳",
        spell: "Luoyang",
        label: "Luoyang0379",
      },
      { code: "0634", name: "莱芜", spell: "Laiwu", label: "Laiwu0634" },
      {
        code: "0316",
        name: "廊坊",
        spell: "Langfang",
        label: "Langfang0316",
      },
      { code: "0891", name: "拉萨", spell: "Lasa", label: "Lasa0891" },
      { code: "0833", name: "乐山", spell: "Leshan", label: "Leshan0833" },
      {
        code: "0834",
        name: "凉山",
        spell: "Liangshan",
        label: "Liangshan0834",
      },
      {
        code: "0419",
        name: "辽阳",
        spell: "Liaoyang",
        label: "Liaoyang0419",
      },
      {
        code: "0437",
        name: "辽源",
        spell: "Liaoyuan",
        label: "Liaoyuan0437",
      },
      {
        code: "0888",
        name: "丽江",
        spell: "Lijiang",
        label: "Lijiang0888",
      },
      {
        code: "0883",
        name: "临沧",
        spell: "Lincang",
        label: "Lincang0883",
      },
      { code: "0357", name: "临汾", spell: "Linfen", label: "Linfen0357" },
      { code: "0930", name: "临夏", spell: "Linxia", label: "Linxia0930" },
      { code: "0894", name: "林芝", spell: "Linzhi", label: "Linzhi0894" },
      {
        code: "0858",
        name: "六盘水",
        spell: "Liupanshui",
        label: "Liupanshui0858",
      },
      {
        code: "0939",
        name: "陇南",
        spell: "Longnan",
        label: "Longnan0939",
      },
      { code: "0738", name: "娄底", spell: "Loudi", label: "Loudi0738" },
      { code: "0395", name: "漯河", spell: "Luohe", label: "Luohe0395" },
      { code: "0830", name: "泸州", spell: "Luzhou", label: "Luzhou0830" },
      {
        code: "0358",
        name: "吕梁",
        spell: "Lvliang",
        label: "Lvliang0358",
      },
      {
        code: "0751",
        name: "乐昌",
        spell: "Lechang",
        label: "Lechang0751",
      },
      {
        code: "0759",
        name: "雷州",
        spell: "Leizhou",
        label: "Leizhou0759",
      },
      { code: "0315", name: "乐亭", spell: "Leting", label: "Leting0315" },
      {
        code: "0799",
        name: "莲花",
        spell: "Lianhua",
        label: "Lianhua0799",
      },
      { code: "0576", name: "临海", spell: "Linhai", label: "Linhai0576" },
      {
        code: "0766",
        name: "罗定",
        spell: "Luoding",
        label: "Luoding0766",
      },
    ],
    M: [
      {
        code: "0816",
        name: "绵阳",
        spell: "Mianyang",
        label: "Mianyang0816",
      },
      {
        code: "0453",
        name: "牡丹江",
        spell: "Mudanjiang",
        label: "Mudanjiang0453",
      },
    ],
    N: [
      {
        code: "0817",
        name: "南充",
        spell: "Nanchong",
        label: "Nanchong0817",
      },
      {
        code: "0377",
        name: "南阳",
        spell: "Nanyang",
        label: "Nanyang0377",
      },
      { code: "0896", name: "那曲", spell: "Naqu", label: "Naqu0896" },
      {
        code: "0832",
        name: "内江",
        spell: "Neijiang",
        label: "Neijiang0832",
      },
      {
        code: "0886",
        name: "怒江",
        spell: "Nujiang",
        label: "Nujiang0886",
      },
      { code: "0754", name: "南澳", spell: "Nanao", label: "Nanao0754" },
    ],
    P: [
      { code: "0427", name: "盘锦", spell: "Panjin", label: "Panjin0427" },
      {
        code: "0812",
        name: "攀枝花",
        spell: "Panzhihua",
        label: "Panzhihua0812",
      },
      {
        code: "0375",
        name: "平顶山",
        spell: "Pingdingshan",
        label: "Pingdingshan0375",
      },
      {
        code: "0933",
        name: "平凉",
        spell: "Pingliang",
        label: "Pingliang0933",
      },
      { code: "0879", name: "普洱", spell: "Puer", label: "Puer0879" },
      { code: "0594", name: "莆田", spell: "Putian", label: "Putian0594" },
      { code: "0393", name: "濮阳", spell: "Puyang", label: "Puyang0393" },
    ],
    Q: [
      {
        code: "0855",
        name: "黔东",
        spell: "Qiandong",
        label: "Qiandong0855",
      },
      {
        code: "0854",
        name: "黔南",
        spell: "Qiannan",
        label: "Qiannan0854",
      },
      {
        code: "0859",
        name: "黔西南",
        spell: "Qianxinan",
        label: "Qianxinan0859",
      },
      {
        code: "0934",
        name: "庆阳",
        spell: "Qingyang",
        label: "Qingyang0934",
      },
      {
        code: "0335",
        name: "秦皇岛",
        spell: "Qinhuangdao",
        label: "Qinhuangdao0335",
      },
      {
        code: "0777",
        name: "钦州",
        spell: "Qinzhou",
        label: "Qinzhou0777",
      },
      {
        code: "0452",
        name: "齐齐哈尔",
        spell: "Qiqihaer",
        label: "Qiqihaer0452",
      },
      {
        code: "0464",
        name: "七台河",
        spell: "Qitaihe",
        label: "Qitaihe0464",
      },
      { code: "0874", name: "曲靖", spell: "Qujing", label: "Qujing0874" },
    ],
    R: [
      { code: "0892", name: "日喀则", spell: "Rikaze", label: "Rikaze0892" },
      {
        code: "0631",
        name: "荣成",
        spell: "Rongcheng",
        label: "Rongcheng0631",
      },
    ],
    S: [
      {
        code: "0398",
        name: "三门峡",
        spell: "Sanmenxia",
        label: "Sanmenxia0398",
      },
      {
        code: "021",
        name: "上海",
        spell: "Shanghai",
        label: "Shanghai021",
      },
      {
        code: "0755",
        name: "深圳",
        spell: "Shenzhen",
        label: "Shenzhen0755",
      },
      { code: "0899", name: "三亚", spell: "Sanya", label: "Sanya0899" },
      {
        code: "0914",
        name: "商洛",
        spell: "Shangluo",
        label: "Shangluo0914",
      },
      {
        code: "0370",
        name: "商丘",
        spell: "Shangqiu",
        label: "Shangqiu0370",
      },
      {
        code: "0893",
        name: "山南",
        spell: "Shannan",
        label: "Shannan0893",
      },
      {
        code: "0575",
        name: "绍兴",
        spell: "Shaoxing",
        label: "Shaoxing0575",
      },
      {
        code: "0739",
        name: "邵阳",
        spell: "Shaoyang",
        label: "Shaoyang0739",
      },
      { code: "0719", name: "十堰", spell: "Shiyan", label: "Shiyan0719" },
      {
        code: "0952",
        name: "石嘴山",
        spell: "Shizuishan",
        label: "Shizuishan0952",
      },
      {
        code: "0469",
        name: "双鸭山",
        spell: "Shuangyashan",
        label: "Shuangyashan0469",
      },
      {
        code: "0349",
        name: "朔州",
        spell: "Shuozhou",
        label: "Shuozhou0349",
      },
      { code: "0434", name: "四平", spell: "Siping", label: "Siping0434" },
      {
        code: "0438",
        name: "松原",
        spell: "Songyuan",
        label: "Songyuan0438",
      },
      { code: "0455", name: "绥化", spell: "Suihua", label: "Suihua0455" },
      {
        code: "0825",
        name: "遂宁",
        spell: "Suining",
        label: "Suining0825",
      },
      {
        code: "0722",
        name: "随州",
        spell: "Suizhou",
        label: "Suizhou0722",
      },
      { code: "0527", name: "宿迁", spell: "Suqian", label: "Suqian0527" },
    ],
    T: [
      {
        code: "0901",
        name: "塔城地",
        spell: "Tachengdi",
        label: "Tachengdi0901",
      },
      { code: "022", name: "天津", spell: "Tianjin", label: "Tianjin022" },
      {
        code: "0351",
        name: "太原",
        spell: "Taiyuan",
        label: "Taiyuan0351",
      },
      {
        code: "0938",
        name: "天水",
        spell: "Tianshui",
        label: "Tianshui0938",
      },
      {
        code: "0410",
        name: "铁岭",
        spell: "Tieling",
        label: "Tieling0410",
      },
      {
        code: "0919",
        name: "铜川",
        spell: "Tongchuan",
        label: "Tongchuan0919",
      },
      {
        code: "0435",
        name: "通化",
        spell: "Tonghua",
        label: "Tonghua0435",
      },
      {
        code: "0475",
        name: "通辽",
        spell: "Tongliao",
        label: "Tongliao0475",
      },
      {
        code: "0562",
        name: "铜陵",
        spell: "Tongling",
        label: "Tongling0562",
      },
      {
        code: "0856",
        name: "铜仁",
        spell: "Tongren",
        label: "Tongren0856",
      },
      {
        code: "0995",
        name: "吐鲁番",
        spell: "Tulufan",
        label: "Tulufan0995",
      },
      {
        code: "0623",
        name: "滕州",
        spell: "Tengzhou",
        label: "Tengzhou0623",
      },
    ],
    W: [
      { code: "0913", name: "渭南", spell: "Weinan", label: "Weinan0913" },
      { code: "027", name: "武汉", spell: "Wuhan", label: "Wuhan027" },
      {
        code: "0876",
        name: "文山",
        spell: "Wenshan",
        label: "Wenshan0876",
      },
      { code: "0473", name: "乌海", spell: "Wuhai", label: "Wuhai0473" },
      {
        code: "0474",
        name: "乌兰察布",
        spell: "Wulanchabu",
        label: "Wulanchabu0474",
      },
      {
        code: "0991",
        name: "乌鲁木齐",
        spell: "Wulumuqi",
        label: "Wulumuqi0991",
      },
      {
        code: "0953",
        name: "吴忠",
        spell: "Wuzhong",
        label: "Wuzhong0953",
      },
    ],
    X: [
      {
        code: "0710",
        name: "襄樊",
        spell: "Xiangfan",
        label: "Xiangfan0710",
      },
      { code: "0592", name: "厦门", spell: "Xiamen", label: "Xiamen0592" },
      {
        code: "0374",
        name: "许昌",
        spell: "Xuchang",
        label: "Xuchang0374",
      },
      {
        code: "0732",
        name: "湘潭",
        spell: "Xiangtan",
        label: "Xiangtan0732",
      },
      {
        code: "0743",
        name: "湘西",
        spell: "Xiangxi",
        label: "Xiangxi0743",
      },
      {
        code: "0715",
        name: "咸宁",
        spell: "Xianning",
        label: "Xianning0715",
      },
      {
        code: "0712",
        name: "孝感",
        spell: "Xiaogan",
        label: "Xiaogan0712",
      },
      {
        code: "0479",
        name: "锡林郭勒盟",
        spell: "Xilinguolemeng",
        label: "Xilinguolemeng0479",
      },
      {
        code: "0482",
        name: "兴安盟",
        spell: "Xinganmeng",
        label: "Xinganmeng0482",
      },
      {
        code: "0319",
        name: "邢台",
        spell: "Xingtai",
        label: "Xingtai0319",
      },
      { code: "0971", name: "西宁", spell: "Xining", label: "Xining0971" },
      {
        code: "0373",
        name: "新乡",
        spell: "Xinxiang",
        label: "Xinxiang0373",
      },
      {
        code: "0376",
        name: "信阳",
        spell: "Xinyang",
        label: "Xinyang0376",
      },
      {
        code: "0350",
        name: "忻州",
        spell: "Xinzhou",
        label: "Xinzhou0350",
      },
      {
        code: "0691",
        name: "西双版纳",
        spell: "Xishuangbanna",
        label: "Xishuangbanna0691",
      },
    ],
    Y: [
      { code: "0835", name: "雅安", spell: "Yaan", label: "Yaan0835" },
      { code: "0911", name: "延安", spell: "Yanan", label: "Yanan0911" },
      {
        code: "0433",
        name: "延边",
        spell: "Yanbian",
        label: "Yanbian0433",
      },
      {
        code: "0662",
        name: "阳江",
        spell: "Yangjiang",
        label: "Yangjiang0662",
      },
      {
        code: "0353",
        name: "阳泉",
        spell: "Yangquan",
        label: "Yangquan0353",
      },
      { code: "0831", name: "宜宾", spell: "Yibin", label: "Yibin0831" },
      {
        code: "0717",
        name: "宜昌",
        spell: "Yichang",
        label: "Yichang0717",
      },
      { code: "0458", name: "伊春", spell: "Yichun", label: "Yichun0458" },
      {
        code: "0999",
        name: "伊犁哈萨克",
        spell: "Yilihasake",
        label: "Yilihasake0999",
      },
      {
        code: "0951",
        name: "银川",
        spell: "Yinchuan",
        label: "Yinchuan0951",
      },
      {
        code: "0417",
        name: "营口",
        spell: "Yingkou",
        label: "Yingkou0417",
      },
      { code: "0737", name: "益阳", spell: "Yiyang", label: "Yiyang0737" },
      {
        code: "0746",
        name: "永州",
        spell: "Yongzhou",
        label: "Yongzhou0746",
      },
      {
        code: "0730",
        name: "岳阳",
        spell: "Yueyang",
        label: "Yueyang0730",
      },
      { code: "0912", name: "榆林", spell: "Yulin", label: "Yulin0912" },
      {
        code: "0359",
        name: "运城",
        spell: "Yuncheng",
        label: "Yuncheng0359",
      },
      { code: "0976", name: "玉树", spell: "Yushu", label: "Yushu0976" },
      { code: "0877", name: "玉溪", spell: "Yuxi", label: "Yuxi0877" },
    ],
    Z: [
      {
        code: "0760",
        name: "中山",
        spell: "Zhongshan",
        label: "Zhongshan0760",
      },
      { code: "0756", name: "珠海", spell: "Zhuhai", label: "Zhuhai0756" },
      {
        code: "0744",
        name: "张家界",
        spell: "Zhangjiajie",
        label: "Zhangjiajie0744",
      },
      {
        code: "0313",
        name: "张家口",
        spell: "Zhangjiakou",
        label: "Zhangjiakou0313",
      },
      {
        code: "0936",
        name: "张掖",
        spell: "Zhangye",
        label: "Zhangye0936",
      },
      {
        code: "0870",
        name: "昭通",
        spell: "Zhaotong",
        label: "Zhaotong0870",
      },
      {
        code: "0955",
        name: "中卫",
        spell: "Zhongwei",
        label: "Zhongwei0955",
      },
      {
        code: "0394",
        name: "周口",
        spell: "Zhoukou",
        label: "Zhoukou0394",
      },
      {
        code: "0396",
        name: "驻马店",
        spell: "Zhumadian",
        label: "Zhumadian0396",
      },
      { code: "0813", name: "自贡", spell: "Zigong", label: "Zigong0813" },
      { code: "0852", name: "遵义", spell: "Zunyi", label: "Zunyi0852" },
    ],
  },
  citiesByProvince: {
    A: [
      {
        provice: "安徽省",
        cities: [
          { code: "0556", name: "安庆", spell: "Anqing", label: "Anqing0556" },
          { code: "0551", name: "合肥", spell: "Hefei", label: "Hefei0551" },
          {
            code: "0562",
            name: "铜陵",
            spell: "Tongling",
            label: "Tongling0562",
          },
          {
            code: "0555",
            name: "马鞍山",
            spell: "Maanshan",
            label: "Maanshan0555",
          },
        ],
      },
    ],
    F: [
      {
        provice: "福建省",
        cities: [
          { code: "0592", name: "厦门", spell: "Xiamen", label: "Xiamen0592" },
          {
            code: "0595",
            name: "泉州",
            spell: "Quanzhou",
            label: "Quanzhou0595",
          },
          { code: "0594", name: "莆田", spell: "Putian", label: "Putian0594" },
        ],
      },
    ],
    G: [
      {
        provice: "甘肃省",
        cities: [
          {
            code: "0931",
            name: "兰州",
            spell: "Lanzhou",
            label: "Lanzhou0931",
          },
          { code: "0932", name: "定西", spell: "Dingxi", label: "Dingxi0932" },
          {
            code: "0933",
            name: "平凉",
            spell: "Pingliang",
            label: "Pingliang0933",
          },
          {
            code: "0934",
            name: "庆阳",
            spell: "Qingyang",
            label: "Qingyang0934",
          },
        ],
      },
      {
        provice: "广东省",
        cities: [
          {
            code: "020",
            name: "广州",
            spell: "Guangzhou",
            label: "Guangzhou020",
          },
          {
            code: "0769",
            name: "东莞",
            spell: "Dongguan",
            label: "Dongguan0769",
          },
          {
            code: "0770",
            name: "防城港",
            spell: "Fangchenggang",
            label: "Fangchenggang0770",
          },
        ],
      },
      {
        provice: "广西壮族自治区",
        cities: [
          { code: "0773", name: "桂林", spell: "Guilin", label: "Guilin0773" },
          { code: "0774", name: "贺州", spell: "Hezhou", label: "Hezhou0774" },
        ],
      },
      {
        provice: "贵州省",
        cities: [
          {
            code: "0851",
            name: "贵阳",
            spell: "Guiyang",
            label: "Guiyang0851",
          },
          { code: "0852", name: "遵义", spell: "Zunyi", label: "Zunyi0852" },
          { code: "0853", name: "安顺", spell: "Anshun", label: "Anshun0853" },
          {
            code: "0854",
            name: "黔南",
            spell: "Qiannan",
            label: "Qiannan0854",
          },
          {
            code: "0855",
            name: "黔东",
            spell: "Qiandong",
            label: "Qiandong0855",
          },
        ],
      },
    ],
    H: [
      {
        provice: "海南省",
        cities: [
          { code: "0899", name: "三亚", spell: "Sanya", label: "Sanya0899" },
          { code: "0898", name: "海口", spell: "Haikou", label: "Haikou0898" },
        ],
      },
      {
        provice: "河北省",
        cities: [
          {
            code: "0311",
            name: "石家庄",
            spell: "Shijiazhuang",
            label: "Shijiazhuang0311",
          },
          {
            code: "0313",
            name: "张家口",
            spell: "Zhangjiakou",
            label: "Zhangjiakou0313",
          },
          {
            code: "0314",
            name: "承德",
            spell: "Chengde",
            label: "Chengde0314",
          },
          {
            code: "0312",
            name: "保定",
            spell: "Baoding",
            label: "Baoding0312",
          },
        ],
      },
      {
        provice: "黑龙江省",
        cities: [
          {
            code: "0453",
            name: "牡丹江",
            spell: "Mudanjiang",
            label: "Mudanjiang0453",
          },
          {
            code: "0451",
            name: "哈尔滨",
            spell: "Haerbin",
            label: "Haerbin0451",
          },
          {
            code: "0452",
            name: "齐齐哈尔",
            spell: "Qiqihaer",
            label: "Qiqihaer0452",
          },
        ],
      },
      {
        provice: "河南省",
        cities: [
          {
            code: "0371",
            name: "郑州",
            spell: "Zhengzhou",
            label: "Zhengzhou0371",
          },
          { code: "0372", name: "安阳", spell: "Anyang", label: "Anyang0372" },
          {
            code: "0373",
            name: "新乡",
            spell: "Xinxiang",
            label: "Xinxiang0373",
          },
          {
            code: "0374",
            name: "许昌",
            spell: "Xuchang",
            label: "Xuchang0374",
          },
          {
            code: "0375",
            name: "平顶山",
            spell: "Pingdingshan",
            label: "Pingdingshan0375",
          },
        ],
      },
      {
        provice: "湖北省",
        cities: [
          { code: "027", name: "武汉", spell: "Wuhan", label: "Wuhan027" },
        ],
      },
      {
        provice: "湖南省",
        cities: [
          {
            code: "0731",
            name: "长沙",
            spell: "Changsha",
            label: "Changsha0731",
          },
          {
            code: "0732",
            name: "湘潭",
            spell: "Xiangtan",
            label: "Xiangtan0732",
          },
          {
            code: "0734",
            name: "衡阳",
            spell: "Hengyang",
            label: "Hengyang0734",
          },
        ],
      },
    ],
    zxs: [
      {
        provice: "直辖市",
        cities: [
          { code: "010", name: "北京", spell: "Beijing", label: "Beijing010" },
          {
            code: "021",
            name: "上海",
            spell: "Shanghai",
            label: "Shanghai021",
          },
          { code: "022", name: "天津", spell: "Tianjin", label: "Tianjin022" },
          {
            code: "023",
            name: "重庆",
            spell: "Chongqing",
            label: "Chongqing023",
          },
        ],
      },
    ],
    gat: [
      {
        provice: "港澳台",
        cities: [
          {
            code: "XiangGang",
            name: "香港",
            spell: "XiangGang",
            label: "XiangGang",
          },
          {
            code: "Aomen",
            name: "澳门",
            spell: "Aomen",
            label: "Aomen",
          },
          { code: "Taiwan", name: "台湾", spell: "Taiwan", label: "Taiwan" },
        ],
      },
    ],
    O: [
      {
        provice: "其他",
        cities: [
          { code: "other01", name: "其他1", spell: "qita1", label: "qita01" },
          { code: "other02", name: "其他2", spell: "qita2", label: "qita02" },
          { code: "other03", name: "其他3", spell: "qita3", label: "qita03" },
          { code: "other04", name: "其他4", spell: "qita4", label: "qita04" },
          { code: "other05", name: "其他5", spell: "qita5", label: "qita05" },
          { code: "othermore", name: "...", spell: "othermore", label: "othermore" },
        ],
      },
    ],
  },
};
