export const EXPORT_NAME = 'export'
export const IMPORT_NAME = 'import'
export const DELETE_USER_NAME = 'delete-user'
export const CHECK_USER_INFO_NAME = 'check-user-info'
export const ROLE_ASSIGN_NAME = 'role-assign'